Use compose input plugin fallback only if key direction is disabled
maliit/framework pull request #98
Opened 2022-04-08 12:55 UTC by pvuorela

Otherwise a hardware keyboard plugin would be fighting with the compose
plugin.

Also removed an unnecessary null check.

2022-04-08 20:08 UTC, dobey requested changes
Can you explain how to test this? Should it be tested in one of the existing unit or functional tests, if possible?

2022-04-11 07:29 UTC, pvuorela commented
> Can you explain how to test this? 

Create an input method plugin that implements hardware keyboard handling and uses the key redirection :) Tbh didn't create such myself now, the commit that went in here earlier just seemed broken obviously enough for this feature. On the quite much more common case this can be tested so that the compose plugin fallback keeps working as it used to, redirectKeys is initialized false and gets true only if the input method server side asks it enabled.

The whole feature might be unknown to many, but on Nokia N950 we had a plugin here. It did things like looping over different characters under one hardware button by sending them as preedit string before committing it. Might have had dead key handling too, don't remember the exact details anymore.

> Should it be tested in one of the existing unit or functional tests, if possible?

There are no tests for the input context.

2022-04-11 19:38 UTC, dobey commented
> Create an input method plugin that implements hardware keyboard handling and uses the key redirection :) Tbh didn't create such myself now

I'm not sure anyone ever has? And there are so many things that just aren't clear from either the documentation or code. Trying to understand some of this (as I'm working on handling various hardware events in maliit keyboard to select OSK functions using a gamepad or such), it just seems much of this is just overly complex and was designed to have every possible language be a separate plugin to framework, rather than having one plugin which handles all the languages and correction and other things. To me, it seems it's time to simplify things greatly, and get rid of the distinction between onscreen/hardware/accessory plugins (do any even really exist anymore for the last two?), and make it easier for plugins to handle anything they need to handle without such complexities.

> On the quite much more common case this can be tested so that the compose plugin fallback keeps working as it used to, redirectKeys is initialized false and gets true only if the input method server side asks it enabled.

Is this something that would be readily evident in the current maliit keyboard under Plasma Mobile on a PinePhone for example? Or is this some other hidden complexity that doesn't appear in normal usage?

> The whole feature might be unknown to many, but on Nokia N950 we had a plugin here. It did things like looping over different characters under one hardware button by sending them as preedit string before committing it. Might have had dead key handling too, don't remember the exact details anymore.

Some of this sounds like something I would love to have in current maliit keyboard, but the details of how to implement it currently are too complex. Also, N950 is a basically non-existent thing it seems. Wikipedia article says only 5000 were ever made, and they were given to developers. There is a developer kit on ebay for one, for $15,000 which is obviously not sensible to pay for a dead product to test and compare theoretical features versus what we have now with current keyboard plugins. :)

2022-04-12 06:35 UTC, pvuorela commented
> I'm not sure anyone ever has?

Well, Nokia & that N950, the code exists here for a reason :)

> And there are so many things that just aren't clear from either the documentation or code

Agree with that. Some things are overcomplicated, some exist to support some N9 UI design detail which hasn't been used since. There could be all sorts of API cleanups.

Whether different keyboard plugin types should exist is also a good question. If it can be assumed that there's only a single keyboard plugin then perhaps no. Though for Nokia we had to also support some third party keyboard plugin but still use the common hardware plugin when the hw keyboard was opened.

...But what comes to these changes the different plugin types shouldn't matter. From input context point of view it gets asked to redirect key events and then it should redirect key events. That part should remain whether there are plugin types or not, otherwise all plugins would be forced to implement the key event handling and there shouldn't be compose plugin fallback at all.

> Is this something that would be readily evident in the current maliit keyboard under Plasma Mobile on a PinePhone for example? Or is this some other hidden complexity that doesn't appear in normal usage?

This code has no effect on virtual keyboard in either form. And for hardware keyboard this doesn't have any effect either unless there's something (i.e. a hardware keyboard plugin) asking for key redirection.

This is really quite a simple change. Unless you find something calling setRedirectKeys() this shouldn't have any effect anywhere.

> Some of this sounds like something I would love to have in current maliit keyboard, but the details of how to implement it currently are too complex.

I'd hope I'd have time some day to get back to these . And definitely wouldn't suggest getting a N950 just to test this :) But shouldn't be overly complicated. Just about creating the plugin of type and then handling the key events in some way. Perhaps doing dead keys as preedit, or feeding the written words to word prediction/correction engine.

2022-04-12 07:04 UTC, jpetersen commented
Looks good for me. Let us merge it.

2022-04-12 07:07 UTC, jpetersen approved these changes

2022-04-12 18:34 UTC, dobey commented
> But what comes to these changes the different plugin types shouldn't matter.

Perhaps, but you'll have to forgive, as both you and @jpetersen have not been particularly active in maliit for quite some time, and this PR seemed particularly relevant to questions I have, and with not great documentation it seems here may be the only chance one might have to clarify some things. :)

> From input context point of view it gets asked to redirect key events and then it should redirect key events.

I was looking through this API a bit, and it seems there is no way to do this and also forward events which the plugin doesn't handle, to the client application? How does a plugin handle normal characters as preedit text through the redirect, like you mentioned for the N950 keyboard, but also still allow things like Ctrl+Enter and such to go through to the application directly?

> This is really quite a simple change. Unless you find something calling setRedirectKeys() this shouldn't have any effect anywhere.

I'm not arguing that. I am however, asking if there is any way I can reasonably test it.

> I'd hope I'd have time some day to get back to these . And definitely wouldn't suggest getting a N950 just to test this :) But shouldn't be overly complicated. Just about creating the plugin of type and then handling the key events in some way. Perhaps doing dead keys as preedit, or feeding the written words to word prediction/correction engine.

Right, I want to remove any separation between "OSK" and "hardware" as far as mallit is concerned, so that if you have some hardware input device, you either get a subset or superset of features enabled in maliit keyboard for an enhanced user experience. But right now, there are three types of plugins supported, two of which are mutually exclusive in framework, and the third being accessory which seems to have no clear purpose or example. The more I try to understand the complexity, it seems the more confused I get. Maybe a result of this is that it might be a good time to break API/ABI again and greatly simplify things for a maliit 3.x?

Maybe you and @jpetersen could join the [Matrix Group](https://matrix.to/#/#maliit:matrix.org) I've created as a place for contributors to discuss things? Would be better than waiting for a random PR to discuss things in again in the future. :)

2022-04-12 20:05 UTC, dobey approved these changes

2022-04-12 20:05 UTC, merged

2022-04-13 08:44 UTC, pvuorela commented
> Perhaps, but you'll have to forgive, as both you and @jpetersen have not been particularly active in maliit for quite some time, and this PR seemed particularly relevant to questions I have, and with not great documentation it seems here may be the only chance one might have to clarify some things. :)

Sure, np.

> I was looking through this API a bit, and it seems there is no way to do this and also forward events which the plugin doesn't handle, to the client application? How does a plugin handle normal characters as preedit text through the redirect, like you mentioned for the N950 keyboard, but also still allow things like Ctrl+Enter and such to go through to the application directly?

If a plugin uses key redirection it needs to send back the key events that should go to the app side as key events. In above ctrl+enter case it could perhaps first commit the current word if it's using predictive input and the QKeyEvent after that with sendKeyEvent().

> Right, I want to remove any separation between "OSK" and "hardware" as far as mallit is concerned, so that if you have some hardware input device, you either get a subset or superset of features enabled in maliit keyboard for an enhanced user experience. But right now, there are three types of plugins supported, two of which are mutually exclusive in framework, and the third being accessory which seems to have no clear purpose or example. The more I try to understand the complexity, it seems the more confused I get. Maybe a result of this is that it might be a good time to break API/ABI again and greatly simplify things for a maliit 3.x?

There needs to be some hardware keyboard state tracking and could be there's some need to have plugins that don't bother with hw kbd side, but generally agree that there are many things that could be gotten rid of. 

Like just quickly for example:
- The extension manager thing. Back then we did a toolbar support on top of the keyboard to serve terminal app that needed some extra buttons. Ctrl, tab etc. I wouldn't be surprised if it hasn't been used for anything since but seems still present. Toolbar like better implemented in app side.
- The plugin switching has bunch of code because we had that 3rd party plugin but still wanted layout switching by swiping from screen edges. Wouldn't be surprised either here if nothing has used this complex system since.
- There's some visualization priority things, language notification requests, etc, that might not be needed anymore.

> Maybe you and @jpetersen could join the [Matrix Group](https://matrix.to/#/#maliit:matrix.org) I've created as a place for contributors to discuss things? Would be better than waiting for a random PR to discuss things in again in the future. :)

Could check at some point. Perhaps could also discuss some things async by creating new issues in github?